### ISSUE TITLE
Is that real data?

### ISSUE THREAD

**Issue by fasterthanlime** [charles-l/asdf#1]
Couple of observations! (since I was bored and looked at my github feed):

  * If you rename the file to 'something.sql' I'm fairly certain GitHub will syntax color it appropriately
  * It seems this contains PINs and phone numbers & real names? Probably a good candidate for a private repo, not a public one!

Cheers,
- Amos

**Comment by charles-l** [comment]
@fasterthanlime nah, just random data generated for a school project, so I'm going to delete the repo soon. Thanks though, Amos :)

**Comment by fasterthanlime** [comment]
Ha, phew :)

**Comment by charles-l** [comment]
@fasterthanlime lol
